# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RecrutamentoIOs' do
  pod 'netfox'
  pod 'Kingfisher'
  pod 'Alamofire', '~> 3.0'
  pod 'ModelRocket'
end

target 'RecrutamentoIOsTests' do
  pod 'Quick'
  pod 'Nimble'
end

target 'RecrutamentoIOsUITests' do

end
